from app.ai.prompts.cv_match import CV_MATCH_SYSTEM_PROMPT, CV_MATCH_USER_PROMPT_TEMPLATE
from app.ai.prompts.interview_questions import INTERVIEW_QUESTIONS_SYSTEM_PROMPT, INTERVIEW_QUESTIONS_USER_PROMPT_TEMPLATE
from app.ai.prompts.interview_evaluation import INTERVIEW_EVALUATION_SYSTEM_PROMPT, INTERVIEW_EVALUATION_USER_PROMPT_TEMPLATE

__all__ = [
    "CV_MATCH_SYSTEM_PROMPT",
    "CV_MATCH_USER_PROMPT_TEMPLATE",
    "INTERVIEW_QUESTIONS_SYSTEM_PROMPT",
    "INTERVIEW_QUESTIONS_USER_PROMPT_TEMPLATE",
    "INTERVIEW_EVALUATION_SYSTEM_PROMPT",
    "INTERVIEW_EVALUATION_USER_PROMPT_TEMPLATE",
]
